baseURL = "https://scribus79.github.io/"
#baseURL = "https://scribus79.github.io/PensierieParole-hugo/"
title = "Pensieri, parole e progetti"
#publishDir = "docs"
theme = "hugo-coder"
languagecode = "it"
defaultcontentlanguage = "it"

googleAnalytics = "UA-162037951-1"  

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "pensieri-parole-e-progetti"

[params]
    author = "Karontes"
    info = "Uno scrittore in erba, nerd, smanettore e tante altre cose"
    description = "Karontes personal website"
    keywords = "blog,scrittura,personal"
    avatarurl = "/images/avatar.jpg"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    footercontent = "Il blog e sito personale di K      "

    hidecredits = false
    hidecopyright = false

    rtl = false

    math = true
    custom_css = ["css/custom.css"]

# Social links
#[[params.social]]
#    name = "Github"
#    icon = "fab fa-github fa-2x"
#    weight = 1
#    url = "https://github.com/johndoe/"
#[[params.social]]
#    name = "Gitlab"
#    icon = "fab fa-gitlab fa-2x"
#    weight = 2
#    url = "https://gitlab.com/johndoe/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 1
    url = "https://twitter.com/Kappa69550631"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
[[menu.main]]
    name = "Progetti"
    weight = 3
    url = "/Progetti/"
